[package]
name = "attack"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["blocking", "multipart", "cookies"] }
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter"]}
